backend:
  #name: git-gateway
  name: test-repo
  branch: main
media_folder: public/assets/blog

collections:
  - name: 'posts'
    label: 'Posts'
    singular_label: 'Post'
    description: >
      This is a list of all the posts you've created so far. 
      Click new Post to start writing a new one.
    create: true
    identifier_field: 'title'
    slug: '{{fields.title}}'
    folder: '_posts'
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string', default: '' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - label: 'Cover Image'
        name: 'coverImage'
        widget: 'image'
        required: false
        tagname: ''

      - {
          label: 'Content',
          name: 'content',
          widget: 'markdown',
          hint: 'Main content goes here.',
        }
